# Generated by Django 4.1.4 on 2022-12-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbihome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-regdate']},
        ),
    ]
